### ISSUE TITLE
Usage with eio

### ISSUE THREAD

**Issue by manuraj17** [mirage/ocaml-fsevents#2]
Hello folks,

Thanks for this library! 

I am quite new to OCaml and the environment as such. I wanted to use the `fsevent` wrapper library for a very basic use case. I see that `lwt` is currently used here. The example also works, although I was just curious how could I use this with `eio`. Since, `eio` is working towards as a replacement for `lwt` I got curious. My limited knowledge is not able to figure out how to make use of it. Any pointers or snippets of code will be helpful.

Apologies beforehand if this was the wrong place to ask this question 🙏🏽 

Regards,
Manu

**Comment by talex5** [comment]
You can use any Lwt library from Eio using https://github.com/ocaml-multicore/lwt_eio.

However, this library's `fsevents_lwt.ml` looks very simple and could probably be ported easily by replacing `Lwt_preemptive.detach` with [Eio_unix.run_in_systhread](https://ocaml-multicore.github.io/eio/eio/Eio_unix/index.html#val-run_in_systhread).

**Comment by manuraj17** [comment]
Thanks @talex5. Will check this out then. Closing this issue for now.
